# -*- coding: utf-8 -*-
"""Untitled1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SK9NKMnM2C88vaIgqSXdwoAkOv6lTvCI
"""

import streamlit as st
import numpy as np
import pandas as pd

st.header("divsion")

st.write("Division of 2 given numbers")
a=st.number_input("enter first number")
b=st.number_input("enter second number or divisor")
c=a/b

st.write(c)